### ISSUE TITLE
Player name RBG color codes

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#131]
While RBG color codes are displayed with appropriate colors in the chat, they break in every other ui element such as scoreboard or pazaak.

For example if the player uses:
/name "^xF30DarthFutuza"
It will be displayed as xF30DarthFutuza" everywhere except chat where it will show up in red.
![shot2016-01-14_00-33-36](https://cloud.githubusercontent.com/assets/4450419/12318377/f353e80a-ba56-11e5-81df-d0450f510d48.jpg)

Note: Something like "^1DarthFutuza" is fine.

**Comment by DarthFutuza** [comment]
Fixed scoreboard http://i.imgur.com/yeYih6e.jpg .  Going to try and tackle "Player has joined Team-X" messages next.

**Comment by DarthFutuza** [comment]
Technically not complete yet, as it is still broken on some messages.  But it is now fixed on Player has joined team-x.  http://i.imgur.com/MbuvmFV.jpg Still need to fix pazaak and maybe a few other places I missed

**Comment by DarthFutuza** [comment]
Fixed cross hair player names: http://i.imgur.com/akbi7Nd.jpg

But...it's super hacky.  Need advice I really really shouldn't be using const_cast.

**Comment by DarthFutuza** [comment]
And finishing the final touches: http://i.imgur.com/sCNUP69.png

**Comment by DarthFutuza** [comment]
Okay so I started refactoring this so we can actually use extended color codes for everything instead of lamely converting them to equivalent ^1 color, cuz that's stupid.  Unfortunately one small bug still remains:

"playername has joined the Spectators" gets cut off if the player's name isn't a certain length, compared to the string it is about to display.  

eg: "^x4de[^7JKG^x4de]^xf30DarthFutuzaaaa" works, but "^x4de[^7JKG^x4de]^xf30DarthFutuzaaa" doesn't   

Probably has to do with whether it is moved to a new line or not (either truncates message), happens on all 4, spectators/or teams.  My guess is something isn't measuring the actual string lengths correctly.

Another example works on spectators: "^x3ed[^7JKG^x3ed]^xf30Dart", but doesn't work on "joined bespin cops".

Names always work if you don't mix ^8 color codes with ^xrgb color codes.  So maybe unrelated to sanitizing strings.

Possibly it's because we have a sanitizestring() somewhere that doesn't account for ^xRGB colors?
![shot2016-02-02_19-31-12](https://cloud.githubusercontent.com/assets/4450419/12773463/26ea97e8-c9f9-11e5-98ba-71570240d267.jpg)

help @xycaleth

**Comment by DarthFutuza** [comment]
Another fix from this [commit.](https://github.com/JKGDevs/JediKnightGalaxies/commit/ed414aa8c47c2ed22d943cbc8a229e158fabe542)  Fixed [previous mentioned bug.](https://github.com/JKGDevs/JediKnightGalaxies/issues/131#issuecomment-179015083)

Todo: duplicate the console color displays for RGB, so console messages also work.

**Comment by eezstreet** [comment]
Needs to be split into multiple smaller issues and dealt with on a case-by-case basis. For right now, the majority of problems have been fixed.

**Comment by DarthFutuza** [comment]
What issues still remain to be solved?  By the way thanks for all the work on this eezstreet and ensiform.
